# Przykład 1
time: 0.45
dry: 0.2
wet: 0.8
feedback: 0.8
filter_low_freq: 4000
filter_high_freq: 6000
filter_order: 1

# Przykład 2
time: 0.35
dry: 0.4
wet: 0.6
feedback: 0.4
filter_low_freq: 200
filter_high_freq: 500
filter_order: 4

# Przykład 3
time: 0.65
dry: 0.5
wet: 0.5
feedback: 0.2
filter_low_freq: 200
filter_high_freq: 5000
filter_order: 2
